const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");
const Product = require("../models/product.model");
const Answer = require("../models/answer.model");
const Question = require("../models/question.model");
const Company = require("../models/company.model");

router.get("/download/:productId", async (req, res) => {
  try {
    const { productId } = req.params;
    const product = await Product.findById(productId).populate("companyId");
    const answers = await Answer.find({ productId }).populate("questionId");

    if (!product) return res.status(404).json({ error: "Product not found" });

    // Create PDF
    const doc = new PDFDocument();
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${product.name}-transparency-report.pdf"`
    );
    doc.pipe(res);

    // Header
    doc.fontSize(20).text("🌿 Product Transparency Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(14).text(`Product: ${product.name}`);
    doc.text(`Category: ${product.category}`);
    doc.text(`Company: ${product.companyId?.name || "N/A"}`);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`);
    doc.moveDown(1.5);

    // Questions & Answers
    doc.fontSize(16).text("Transparency Details:", { underline: true });
    doc.moveDown();

    answers.forEach((ans, i) => {
      doc.fontSize(12).text(`${i + 1}. ${ans.questionId.questionText}`, { bold: true });
      doc.fontSize(12).fillColor("#555").text(`→ ${ans.value}`, {
        indent: 20,
        lineGap: 4,
      });
      doc.moveDown();
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).fillColor("#888").text("Generated by Product Transparency Platform © 2025", {
      align: "center",
    });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to generate report" });
  }
});
router.get("/:productId/pdf", async (req, res) => {
  try {
    const { productId } = req.params;
    const product = await Product.findById(productId).populate("companyId");
    const questions = await Question.find({ productId });
    const answers = await Answer.find({ productId });

    const doc = new PDFDocument();
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${product.name}_report.pdf"`
    );
    doc.pipe(res);

    doc.fontSize(18).text(`Product Report: ${product.name}`, { underline: true });
    doc.moveDown();
    doc.fontSize(12).text(`Description: ${product.description}`);
    doc.moveDown();

    questions.forEach((q) => {
      const ans = answers.find((a) => a.questionId.toString() === q._id.toString());
      doc.text(`Q: ${q.text}`);
      doc.text(`A: ${ans ? ans.value : "No answer"}`);
      doc.moveDown();
    });

    doc.end();
  } catch (err) {
    res.status(500).json({ error: "Error generating PDF" });
  }
});

module.exports = router;
